debug: true

branches:
  include: [ master ]
  exclude: [ develop, auto-tag-* ]

build:
  test:
    image: node:6-alpine
    commands:
      - "npm install"
      - "npm update"
  bundle:
    image: node:6-alpine
    commands:
      - "npm prune --production"
    when:
      event: [ push, tag ]

cache:
  mount:
    - node_modules
    - .git